version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1-stretch
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install pylint3
      - run: make check
